application: isranumberdev
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /authenticationmanagement/admin
  script: isranumbers.app
  login: admin

- url: /authenticationmanagement/admin/.*
  script: isranumbers.app
  login: admin

- url: /.*
  script: isranumbers.app

libraries:
- name: jinja2
  version: latest
